Running on device npu:0
Traceback (most recent call last):
  File "vision.py", line 171, in <module>
    main(args)
  File "vision.py", line 105, in main
    predicted = forward(input_tensor, model, args)
  File "vision.py", line 41, in forward
    output_tensor = model(input_tensor)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 624, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torchvision/models/resnet.py", line 155, in forward
    x = self.layer1(x)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 624, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 624, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torchvision/models/resnet.py", line 88, in forward
    out = self.bn3(out)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 624, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 122, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/nn/functional.py", line 1923, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: malloc:/usr1/workspace/PyTorch_Apex_Daily/CODE/c10/npu/NPUCachingAllocator.cpp:293 NPU error, error code is 500000
THPModule_npu_shutdown success.
